### ISSUE TITLE
Non-Standard CSV Format

### ISSUE THREAD

**Issue by matsalgado** [magicsword-io/LOLDrivers#147]
hey guys! :)

I am currently having some troubles to use/import the CSV file obtained from https://www.loldrivers.io/api/drivers.csv because the values are not enclosed within double quotes.

checking other APIs like hijacklibs, abuse.ch and urlhaus I realized that the "standard" is using double quotes.

has anyone faced the same issue?

**Comment by josehelps** [comment]
I need to double check this, might for sure be a issue here, today we are just using the csv lib with writerow here: https://github.com/magicsword-io/LOLDrivers/blob/main/bin/site.py#L11

**Comment by matsalgado** [comment]
idk in which format the `write_drivers_csv` function receives the drivers data, but using [pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html) lib you can do this in a very straightforward way:

Example:
```
import pandas as pd

data = {'Name': ['John', 'Hugo', 'Ana', 'Meg'],
        'Age': [35, 41, 29, 25],
        'City': ['New York', 'Paris', 'SP', 'London']}
        
df = pd.DataFrame(data)

df.to_csv('output.csv', quoting=1, index=False)
```

The parameter **quoting** is responsible for adding (1) or not (0) quotes to the values.

**Comment by josehelps** [comment]
Hey this should be solved @matsalgado let me know please

**Comment by matsalgado** [comment]
hey @josehelps...
I've just tested here and unfortunately, for my case, it has not been solved 😥

Actually I think the column titles should not be enclosed in "" (this is not the reason for my issue, cuz I also tested w/o them and the issue persists) it is more a tip if you want to keep "standard" like the other APIs that I mentioned

but now, I will need to investigate MORE to understand why the values are not being parsed correctly.

anyway, thanks for the update! 😊

**Comment by MHaggis** [comment]
Current generation uses `pandas.DataFrame.to_csv(..., quoting=1, index=False)`, and the current published `drivers.csv` has quoted headers and values. Closing as fixed in current output; if the latest CSV still breaks a parser, please reopen with the parser/error details.
